//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoOOIA.CoordinadorEventoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", ConfigurationName="CoordinadorEventoWS.CoordinadorEventoWS")]
    public interface CoordinadorEventoWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/CoordinadorEventoWS/listarCoordinadorEventoReque" +
            "st", ReplyAction="http://services.OOIA.pucp.edu.pe/CoordinadorEventoWS/listarCoordinadorEventoRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoOOIA.CoordinadorEventoWS.listarCoordinadorEventoResponse listarCoordinadorEvento(ProyectoOOIA.CoordinadorEventoWS.listarCoordinadorEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/CoordinadorEventoWS/listarCoordinadorEventoReque" +
            "st", ReplyAction="http://services.OOIA.pucp.edu.pe/CoordinadorEventoWS/listarCoordinadorEventoRespo" +
            "nse")]
        System.Threading.Tasks.Task<ProyectoOOIA.CoordinadorEventoWS.listarCoordinadorEventoResponse> listarCoordinadorEventoAsync(ProyectoOOIA.CoordinadorEventoWS.listarCoordinadorEventoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/CoordinadorEventoWS/eliminarCoordinadorEventoReq" +
            "uest", ReplyAction="http://services.OOIA.pucp.edu.pe/CoordinadorEventoWS/eliminarCoordinadorEventoRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoOOIA.CoordinadorEventoWS.eliminarCoordinadorEventoResponse eliminarCoordinadorEvento(ProyectoOOIA.CoordinadorEventoWS.eliminarCoordinadorEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/CoordinadorEventoWS/eliminarCoordinadorEventoReq" +
            "uest", ReplyAction="http://services.OOIA.pucp.edu.pe/CoordinadorEventoWS/eliminarCoordinadorEventoRes" +
            "ponse")]
        System.Threading.Tasks.Task<ProyectoOOIA.CoordinadorEventoWS.eliminarCoordinadorEventoResponse> eliminarCoordinadorEventoAsync(ProyectoOOIA.CoordinadorEventoWS.eliminarCoordinadorEventoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/CoordinadorEventoWS/modificarCoordinadorEventoRe" +
            "quest", ReplyAction="http://services.OOIA.pucp.edu.pe/CoordinadorEventoWS/modificarCoordinadorEventoRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoOOIA.CoordinadorEventoWS.modificarCoordinadorEventoResponse modificarCoordinadorEvento(ProyectoOOIA.CoordinadorEventoWS.modificarCoordinadorEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/CoordinadorEventoWS/modificarCoordinadorEventoRe" +
            "quest", ReplyAction="http://services.OOIA.pucp.edu.pe/CoordinadorEventoWS/modificarCoordinadorEventoRe" +
            "sponse")]
        System.Threading.Tasks.Task<ProyectoOOIA.CoordinadorEventoWS.modificarCoordinadorEventoResponse> modificarCoordinadorEventoAsync(ProyectoOOIA.CoordinadorEventoWS.modificarCoordinadorEventoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/CoordinadorEventoWS/insertarCoordinadorEventoReq" +
            "uest", ReplyAction="http://services.OOIA.pucp.edu.pe/CoordinadorEventoWS/insertarCoordinadorEventoRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoOOIA.CoordinadorEventoWS.insertarCoordinadorEventoResponse insertarCoordinadorEvento(ProyectoOOIA.CoordinadorEventoWS.insertarCoordinadorEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.OOIA.pucp.edu.pe/CoordinadorEventoWS/insertarCoordinadorEventoReq" +
            "uest", ReplyAction="http://services.OOIA.pucp.edu.pe/CoordinadorEventoWS/insertarCoordinadorEventoRes" +
            "ponse")]
        System.Threading.Tasks.Task<ProyectoOOIA.CoordinadorEventoWS.insertarCoordinadorEventoResponse> insertarCoordinadorEventoAsync(ProyectoOOIA.CoordinadorEventoWS.insertarCoordinadorEventoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.OOIA.pucp.edu.pe/")]
    public partial class miembroOOIA : miembroPUCP {
        
        private bool estadoField;
        
        private evento[] eventosField;
        
        private int id_coordinadorEventosOOIAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("eventos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public evento[] eventos {
            get {
                return this.eventosField;
            }
            set {
                this.eventosField = value;
                this.RaisePropertyChanged("eventos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id_coordinadorEventosOOIA {
            get {
                return this.id_coordinadorEventosOOIAField;
            }
            set {
                this.id_coordinadorEventosOOIAField = value;
                this.RaisePropertyChanged("id_coordinadorEventosOOIA");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.OOIA.pucp.edu.pe/")]
    public partial class evento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int capacidadField;
        
        private bool estadoField;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private localTime horaFinField;
        
        private localTime horaInicioField;
        
        private int id_coordinadorField;
        
        private int id_eventoField;
        
        private string lugarField;
        
        private string nombreField;
        
        private persona[] ponentesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int capacidad {
            get {
                return this.capacidadField;
            }
            set {
                this.capacidadField = value;
                this.RaisePropertyChanged("capacidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localTime horaFin {
            get {
                return this.horaFinField;
            }
            set {
                this.horaFinField = value;
                this.RaisePropertyChanged("horaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public localTime horaInicio {
            get {
                return this.horaInicioField;
            }
            set {
                this.horaInicioField = value;
                this.RaisePropertyChanged("horaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int id_coordinador {
            get {
                return this.id_coordinadorField;
            }
            set {
                this.id_coordinadorField = value;
                this.RaisePropertyChanged("id_coordinador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int id_evento {
            get {
                return this.id_eventoField;
            }
            set {
                this.id_eventoField = value;
                this.RaisePropertyChanged("id_evento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string lugar {
            get {
                return this.lugarField;
            }
            set {
                this.lugarField = value;
                this.RaisePropertyChanged("lugar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ponentes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public persona[] ponentes {
            get {
                return this.ponentesField;
            }
            set {
                this.ponentesField = value;
                this.RaisePropertyChanged("ponentes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.OOIA.pucp.edu.pe/")]
    public partial class localTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(miembroPUCP))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(miembroOOIA))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.OOIA.pucp.edu.pe/")]
    public abstract partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string correoField;
        
        private string direccionField;
        
        private string dniField;
        
        private int edadField;
        
        private int id_personaField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int edad {
            get {
                return this.edadField;
            }
            set {
                this.edadField = value;
                this.RaisePropertyChanged("edad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int id_persona {
            get {
                return this.id_personaField;
            }
            set {
                this.id_personaField = value;
                this.RaisePropertyChanged("id_persona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(miembroOOIA))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.OOIA.pucp.edu.pe/")]
    public abstract partial class miembroPUCP : persona {
        
        private string contraseñaField;
        
        private System.DateTime fecha_inclusionField;
        
        private bool fecha_inclusionFieldSpecified;
        
        private int id_miembro_pucpField;
        
        private byte[] imagenDePerfilField;
        
        private string usuario_pucpField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
                this.RaisePropertyChanged("contraseña");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fecha_inclusion {
            get {
                return this.fecha_inclusionField;
            }
            set {
                this.fecha_inclusionField = value;
                this.RaisePropertyChanged("fecha_inclusion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_inclusionSpecified {
            get {
                return this.fecha_inclusionFieldSpecified;
            }
            set {
                this.fecha_inclusionFieldSpecified = value;
                this.RaisePropertyChanged("fecha_inclusionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id_miembro_pucp {
            get {
                return this.id_miembro_pucpField;
            }
            set {
                this.id_miembro_pucpField = value;
                this.RaisePropertyChanged("id_miembro_pucp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=3)]
        public byte[] imagenDePerfil {
            get {
                return this.imagenDePerfilField;
            }
            set {
                this.imagenDePerfilField = value;
                this.RaisePropertyChanged("imagenDePerfil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string usuario_pucp {
            get {
                return this.usuario_pucpField;
            }
            set {
                this.usuario_pucpField = value;
                this.RaisePropertyChanged("usuario_pucp");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCoordinadorEvento", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCoordinadorEventoRequest {
        
        public listarCoordinadorEventoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCoordinadorEventoResponse", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCoordinadorEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoOOIA.CoordinadorEventoWS.miembroOOIA[] @return;
        
        public listarCoordinadorEventoResponse() {
        }
        
        public listarCoordinadorEventoResponse(ProyectoOOIA.CoordinadorEventoWS.miembroOOIA[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCoordinadorEvento", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCoordinadorEventoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoOOIA.CoordinadorEventoWS.miembroOOIA coordinador;
        
        public eliminarCoordinadorEventoRequest() {
        }
        
        public eliminarCoordinadorEventoRequest(ProyectoOOIA.CoordinadorEventoWS.miembroOOIA coordinador) {
            this.coordinador = coordinador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCoordinadorEventoResponse", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCoordinadorEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarCoordinadorEventoResponse() {
        }
        
        public eliminarCoordinadorEventoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCoordinadorEvento", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarCoordinadorEventoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoOOIA.CoordinadorEventoWS.miembroOOIA coordinador;
        
        public modificarCoordinadorEventoRequest() {
        }
        
        public modificarCoordinadorEventoRequest(ProyectoOOIA.CoordinadorEventoWS.miembroOOIA coordinador) {
            this.coordinador = coordinador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCoordinadorEventoResponse", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarCoordinadorEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarCoordinadorEventoResponse() {
        }
        
        public modificarCoordinadorEventoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCoordinadorEvento", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCoordinadorEventoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoOOIA.CoordinadorEventoWS.miembroOOIA coordinador;
        
        public insertarCoordinadorEventoRequest() {
        }
        
        public insertarCoordinadorEventoRequest(ProyectoOOIA.CoordinadorEventoWS.miembroOOIA coordinador) {
            this.coordinador = coordinador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCoordinadorEventoResponse", WrapperNamespace="http://services.OOIA.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCoordinadorEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.OOIA.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarCoordinadorEventoResponse() {
        }
        
        public insertarCoordinadorEventoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CoordinadorEventoWSChannel : ProyectoOOIA.CoordinadorEventoWS.CoordinadorEventoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CoordinadorEventoWSClient : System.ServiceModel.ClientBase<ProyectoOOIA.CoordinadorEventoWS.CoordinadorEventoWS>, ProyectoOOIA.CoordinadorEventoWS.CoordinadorEventoWS {
        
        public CoordinadorEventoWSClient() {
        }
        
        public CoordinadorEventoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CoordinadorEventoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoordinadorEventoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoordinadorEventoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoOOIA.CoordinadorEventoWS.listarCoordinadorEventoResponse ProyectoOOIA.CoordinadorEventoWS.CoordinadorEventoWS.listarCoordinadorEvento(ProyectoOOIA.CoordinadorEventoWS.listarCoordinadorEventoRequest request) {
            return base.Channel.listarCoordinadorEvento(request);
        }
        
        public ProyectoOOIA.CoordinadorEventoWS.miembroOOIA[] listarCoordinadorEvento() {
            ProyectoOOIA.CoordinadorEventoWS.listarCoordinadorEventoRequest inValue = new ProyectoOOIA.CoordinadorEventoWS.listarCoordinadorEventoRequest();
            ProyectoOOIA.CoordinadorEventoWS.listarCoordinadorEventoResponse retVal = ((ProyectoOOIA.CoordinadorEventoWS.CoordinadorEventoWS)(this)).listarCoordinadorEvento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoOOIA.CoordinadorEventoWS.listarCoordinadorEventoResponse> ProyectoOOIA.CoordinadorEventoWS.CoordinadorEventoWS.listarCoordinadorEventoAsync(ProyectoOOIA.CoordinadorEventoWS.listarCoordinadorEventoRequest request) {
            return base.Channel.listarCoordinadorEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoOOIA.CoordinadorEventoWS.listarCoordinadorEventoResponse> listarCoordinadorEventoAsync() {
            ProyectoOOIA.CoordinadorEventoWS.listarCoordinadorEventoRequest inValue = new ProyectoOOIA.CoordinadorEventoWS.listarCoordinadorEventoRequest();
            return ((ProyectoOOIA.CoordinadorEventoWS.CoordinadorEventoWS)(this)).listarCoordinadorEventoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoOOIA.CoordinadorEventoWS.eliminarCoordinadorEventoResponse ProyectoOOIA.CoordinadorEventoWS.CoordinadorEventoWS.eliminarCoordinadorEvento(ProyectoOOIA.CoordinadorEventoWS.eliminarCoordinadorEventoRequest request) {
            return base.Channel.eliminarCoordinadorEvento(request);
        }
        
        public int eliminarCoordinadorEvento(ProyectoOOIA.CoordinadorEventoWS.miembroOOIA coordinador) {
            ProyectoOOIA.CoordinadorEventoWS.eliminarCoordinadorEventoRequest inValue = new ProyectoOOIA.CoordinadorEventoWS.eliminarCoordinadorEventoRequest();
            inValue.coordinador = coordinador;
            ProyectoOOIA.CoordinadorEventoWS.eliminarCoordinadorEventoResponse retVal = ((ProyectoOOIA.CoordinadorEventoWS.CoordinadorEventoWS)(this)).eliminarCoordinadorEvento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoOOIA.CoordinadorEventoWS.eliminarCoordinadorEventoResponse> ProyectoOOIA.CoordinadorEventoWS.CoordinadorEventoWS.eliminarCoordinadorEventoAsync(ProyectoOOIA.CoordinadorEventoWS.eliminarCoordinadorEventoRequest request) {
            return base.Channel.eliminarCoordinadorEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoOOIA.CoordinadorEventoWS.eliminarCoordinadorEventoResponse> eliminarCoordinadorEventoAsync(ProyectoOOIA.CoordinadorEventoWS.miembroOOIA coordinador) {
            ProyectoOOIA.CoordinadorEventoWS.eliminarCoordinadorEventoRequest inValue = new ProyectoOOIA.CoordinadorEventoWS.eliminarCoordinadorEventoRequest();
            inValue.coordinador = coordinador;
            return ((ProyectoOOIA.CoordinadorEventoWS.CoordinadorEventoWS)(this)).eliminarCoordinadorEventoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoOOIA.CoordinadorEventoWS.modificarCoordinadorEventoResponse ProyectoOOIA.CoordinadorEventoWS.CoordinadorEventoWS.modificarCoordinadorEvento(ProyectoOOIA.CoordinadorEventoWS.modificarCoordinadorEventoRequest request) {
            return base.Channel.modificarCoordinadorEvento(request);
        }
        
        public int modificarCoordinadorEvento(ProyectoOOIA.CoordinadorEventoWS.miembroOOIA coordinador) {
            ProyectoOOIA.CoordinadorEventoWS.modificarCoordinadorEventoRequest inValue = new ProyectoOOIA.CoordinadorEventoWS.modificarCoordinadorEventoRequest();
            inValue.coordinador = coordinador;
            ProyectoOOIA.CoordinadorEventoWS.modificarCoordinadorEventoResponse retVal = ((ProyectoOOIA.CoordinadorEventoWS.CoordinadorEventoWS)(this)).modificarCoordinadorEvento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoOOIA.CoordinadorEventoWS.modificarCoordinadorEventoResponse> ProyectoOOIA.CoordinadorEventoWS.CoordinadorEventoWS.modificarCoordinadorEventoAsync(ProyectoOOIA.CoordinadorEventoWS.modificarCoordinadorEventoRequest request) {
            return base.Channel.modificarCoordinadorEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoOOIA.CoordinadorEventoWS.modificarCoordinadorEventoResponse> modificarCoordinadorEventoAsync(ProyectoOOIA.CoordinadorEventoWS.miembroOOIA coordinador) {
            ProyectoOOIA.CoordinadorEventoWS.modificarCoordinadorEventoRequest inValue = new ProyectoOOIA.CoordinadorEventoWS.modificarCoordinadorEventoRequest();
            inValue.coordinador = coordinador;
            return ((ProyectoOOIA.CoordinadorEventoWS.CoordinadorEventoWS)(this)).modificarCoordinadorEventoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoOOIA.CoordinadorEventoWS.insertarCoordinadorEventoResponse ProyectoOOIA.CoordinadorEventoWS.CoordinadorEventoWS.insertarCoordinadorEvento(ProyectoOOIA.CoordinadorEventoWS.insertarCoordinadorEventoRequest request) {
            return base.Channel.insertarCoordinadorEvento(request);
        }
        
        public int insertarCoordinadorEvento(ProyectoOOIA.CoordinadorEventoWS.miembroOOIA coordinador) {
            ProyectoOOIA.CoordinadorEventoWS.insertarCoordinadorEventoRequest inValue = new ProyectoOOIA.CoordinadorEventoWS.insertarCoordinadorEventoRequest();
            inValue.coordinador = coordinador;
            ProyectoOOIA.CoordinadorEventoWS.insertarCoordinadorEventoResponse retVal = ((ProyectoOOIA.CoordinadorEventoWS.CoordinadorEventoWS)(this)).insertarCoordinadorEvento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoOOIA.CoordinadorEventoWS.insertarCoordinadorEventoResponse> ProyectoOOIA.CoordinadorEventoWS.CoordinadorEventoWS.insertarCoordinadorEventoAsync(ProyectoOOIA.CoordinadorEventoWS.insertarCoordinadorEventoRequest request) {
            return base.Channel.insertarCoordinadorEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoOOIA.CoordinadorEventoWS.insertarCoordinadorEventoResponse> insertarCoordinadorEventoAsync(ProyectoOOIA.CoordinadorEventoWS.miembroOOIA coordinador) {
            ProyectoOOIA.CoordinadorEventoWS.insertarCoordinadorEventoRequest inValue = new ProyectoOOIA.CoordinadorEventoWS.insertarCoordinadorEventoRequest();
            inValue.coordinador = coordinador;
            return ((ProyectoOOIA.CoordinadorEventoWS.CoordinadorEventoWS)(this)).insertarCoordinadorEventoAsync(inValue);
        }
    }
}
